version: '3'
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: PHP
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    networks:
      - mahdiyar
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: MYSQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chatroom
      MYSQL_USER: mahdiyar
      MYSQL_PASSWORD: 123456
    ports:
      - "9906:3306"
    networks:
      - mahdiyar
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    links:
    - mysql
    restart: always
    ports:
      - 8080:80
    networks:
      - mahdiyar


networks:
  mahdiyar:
